// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3Qpg3rIfQjg2q7y2kIJr_Sns8iLbDhok',
    appId: '1:747409159242:web:030ba182baf76e2064a2b3',
    messagingSenderId: '747409159242',
    projectId: 'project3-hungerstation',
    authDomain: 'project3-hungerstation.firebaseapp.com',
    storageBucket: 'project3-hungerstation.appspot.com',
    measurementId: 'G-V57F362BHV',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtQPAW04-DicSVYsYkIxHGwSTfSFmSLOU',
    appId: '1:747409159242:ios:d0f03ae9c9eb259f64a2b3',
    messagingSenderId: '747409159242',
    projectId: 'project3-hungerstation',
    storageBucket: 'project3-hungerstation.appspot.com',
    iosClientId: '747409159242-pj2o28lj2f7d3fuan3eiv0gksabnlb90.apps.googleusercontent.com',
    iosBundleId: 'com.example.project3',
  );
}
